# Generated by Django 5.2.7 on 2025-10-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сделки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('stage', models.CharField(choices=[('lead', 'Лид'), ('contact', 'Контакт'), ('proposal', 'Предложение'), ('negotiation', 'Переговоры'), ('won', 'Успех'), ('lost', 'Потерян')], default='lead', max_length=20)),
                ('probability', models.IntegerField(default=0, verbose_name='Вероятность (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_close', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата закрытия')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='clients.client')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
    ]
